### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'yandex_weather' at custom_components/yandex_weather/updater.py

### ISSUE THREAD

**Issue by EvgenyBash** [IATkachenko/HA-YandexWeather#120]
### The problem

В логах появляются такие ошибки

### What version of the integration has the issue?

3.2.5

### What version of Home Assistant Core has the issue?

core-2024.6.1

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Регистратор: homeassistant.util.loop
Источник: util/loop.py:84
Первое сообщение: 20:03:55 (1 сообщений)
Последнее сообщение: 20:03:55

Detected blocking call to open inside the event loop by custom integration 'yandex_weather' at custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f: (offender: /config/custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f:), please create a bug report at https://github.com/IATkachenko/HA-YandexWeather/issues Traceback (most recent call last): 
File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) 
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) 
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() 
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) 
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval await self._async_refresh(log_failures=True, scheduled=True) 
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() 
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() 
File "/config/custom_components/yandex_weather/updater.py", line 260, in update self.process_data(result, r["fact"], CURRENT_WEATHER_ATTRIBUTE_TRANSLATION) 
File "/config/custom_components/yandex_weather/updater.py", line 211, in process_data value = translate_condition( 
File "/config/custom_components/yandex_weather/updater.py", line 137, in translate_condition with open(_translation_location) as f:
```

**Comment by IATkachenko** [comment]
Кажется это ничего не ломает, а просто нам рассказывают что хотят больше асинхронных вызовов.

Посмотрю как улучшить.

**Comment by EvgenyBash** [comment]
> Кажется это ничего не ломает,

Да, интеграция работает, просто в логах валится эта инфа.

**Comment by IATkachenko** [comment]
Со временем поправлю, если Яндекс совсем публичный бесплатный доступ к API не закроет...

**Comment by monoflash** [comment]
У меня то же самое, если вдруг поможет, мой лог:
```
homeassistant[1]: 2024-10-14 23:22:22.175 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/yandex_weather/translations/ru.json',) inside the event loop by custom integration 'yandex_weather' at custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f: (offender: /config/custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f:), please create a bug report at https://github.com/IATkachenko/HA-YandexWeather/issues
homeassistant[1]: For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
homeassistant[1]: Traceback (most recent call last):
homeassistant[1]:   File "<frozen runpy>", line 198, in _run_module_as_main
homeassistant[1]:   File "<frozen runpy>", line 88, in _run_code
homeassistant[1]:   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
homeassistant[1]:     sys.exit(main())
homeassistant[1]:   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
homeassistant[1]:     exit_code = runner.run(runtime_conf)
homeassistant[1]:   File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
homeassistant[1]:     return loop.run_until_complete(setup_and_run_hass(runtime_config))
homeassistant[1]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
homeassistant[1]:     self.run_forever()
homeassistant[1]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
homeassistant[1]:     self._run_once()
homeassistant[1]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
homeassistant[1]:     handle._run()
homeassistant[1]:   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
homeassistant[1]:     self._context.run(self._callback, *self._args)
homeassistant[1]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
homeassistant[1]:     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant[1]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
homeassistant[1]:     self.data = await self._async_update_data()
homeassistant[1]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
homeassistant[1]:     return await self.update_method()
homeassistant[1]:   File "/config/custom_components/yandex_weather/updater.py", line 260, in update
homeassistant[1]:     self.process_data(result, r["fact"], CURRENT_WEATHER_ATTRIBUTE_TRANSLATION)
homeassistant[1]:   File "/config/custom_components/yandex_weather/updater.py", line 211, in process_data
homeassistant[1]:     value = translate_condition(
homeassistant[1]:   File "/config/custom_components/yandex_weather/updater.py", line 137, in translate_condition
homeassistant[1]:     with open(_translation_location) as f:
homeassistant[1]: 
```

**Comment by lunguch** [comment]
Аналогичная проблема. 
2025-02-24 14:20:12.442 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/yandex_weather/translations/ru.json',) inside the event loop by custom integration 'yandex_weather' at custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f: (offender: /config/custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f:), please create a bug report at https://github.com/IATkachenko/HA-YandexWeather/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/yandex_weather/updater.py", line 260, in update
    self.process_data(result, r["fact"], CURRENT_WEATHER_ATTRIBUTE_TRANSLATION)
  File "/config/custom_components/yandex_weather/updater.py", line 211, in process_data
    value = translate_condition(
  File "/config/custom_components/yandex_weather/updater.py", line 137, in translate_condition
    with open(_translation_location) as f:

Примерно в это же время Ха ребутся (segfault). Я не уверен связано ли это, но может кто то предложить решение?

**Comment by IATkachenko** [comment]
В [v4.0.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v4.0.0) удалены переводы состояний.
Если понадобятся и будем возвращать -- сразу сделаю в асинхронном режиме, но похоже HA сам уже не плохо справляется с переводами.
