### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by vgdh** [IATkachenko/HA-YandexWeather#123]
### The problem
```
2024-08-15 15:58:03.625 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/yandex_weather/translations/ru.json',) inside the event loop by custom integration 'yandex_weather' at custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f: (offender: /config/custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f:), please create a bug report at https://github.com/IATkachenko/HA-YandexWeather/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/yandex_weather/updater.py", line 260, in update
    self.process_data(result, r["fact"], CURRENT_WEATHER_ATTRIBUTE_TRANSLATION)
  File "/config/custom_components/yandex_weather/updater.py", line 211, in process_data
    value = translate_condition(
  File "/config/custom_components/yandex_weather/updater.py", line 137, in translate_condition
    with open(_translation_location) as f:
```

### What version of the integration has the issue?

3.2.5

### What version of Home Assistant Core has the issue?

13

### What type of installation are you running?

Home Assistant OS

**Comment by IATkachenko** [comment]
#120 про это. Прикрою как дубликат.
