### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nikrays** [IATkachenko/HA-YandexWeather#44]
### В чем проблема?

Logger: homeassistant.components.weather
Source: util/temperature.py:50
Integration: Weather (documentation, issues)
First occurred: 13:57:58 (2 occurrences)
Last logged: 13:57:58

Error adding entities for domain weather with platform yandex_weather
Error while setting up yandex_weather platform for weather
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/weather.py", line 142, in async_added_to_hass
    f[attribute] = converter(
  File "/usr/src/homeassistant/homeassistant/util/temperature.py", line 50, in convert
    raise ValueError(UNIT_NOT_RECOGNIZED_TEMPLATE.format(from_unit, TEMPERATURE))
ValueError: None is not a recognized temperature unit.
```

### При использовании какой версии интеграции возникает проблема?

1.0

### Какая версия Home Assistant используется?

2022.7

### Какой способ установки Home Assistant используется?

Home Assistant OS

**Comment by IATkachenko** [comment]
Исправлено в [v1.0.2](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v1.0.2)
