### ISSUE TITLE
Ошибка мастера настройки

### ISSUE THREAD

**Issue by iddqd42** [IATkachenko/HA-YandexWeather#5]
Данные о погоде отображаются, но при нажатии кнопки Настройки появляется сообщение: "Ошибка
Не удалось загрузить мастер настройки" 

`2022-01-29 16:07:23 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-29 16:07:23 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration yandex_weather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-29 16:07:25 INFO (MainThread) [custom_components.yandex_weather.updater] Sending API request
2022-01-29 16:07:26 DEBUG (MainThread) [custom_components.yandex_weather.updater] {"now":1643461645,"now_dt":"2022-01-29T13:07:25.986028Z","info":{"url":"https://yandex.com/weather/2?lat=59.95528744\u0026lon=30.46897602","lat":59.955287441121,"lon":30.468976021074923},"fact":{"obs_time":1643461200,"temp":-3,"feels_like":-7,"icon":"ovc","condition":"overcast","wind_speed":2,"wind_dir":"sw","pressure_mm":753,"pressure_pa":1003,"humidity":82,"daytime":"d","polar":false,"season":"winter","wind_gust":6.4},"forecast":{"date":"2022-01-29","date_ts":1643403600,"week":4,"sunrise":"09:19","sunset":"17:02","moon_code":6,"moon_text":"moon-code-6","parts":[{"part_name":"evening","temp_min":-5,"temp_avg":-4,"temp_max":-4,"wind_speed":5.7,"wind_gust":12.2,"wind_dir":"s","pressure_mm":748,"pressure_pa":997,"humidity":85,"prec_mm":0,"prec_prob":0,"prec_period":360,"icon":"bkn_n","condition":"cloudy","feels_like":-11,"daytime":"n","polar":false},{"part_name":"night","temp_min":-4,"temp_avg":-4,"temp_max":-4,"wind_speed":8,"wind_gust":16.5,"wind_dir":"se","pressure_mm":739,"pressure_pa":985,"humidity":82,"prec_mm":1.8,"prec_prob":50,"prec_period":360,"icon":"ovc_+sn","condition":"snow","feels_like":-12,"daytime":"n","polar":false}]}}
2022-01-29 16:07:26 DEBUG (MainThread) [custom_components.yandex_weather.updater] Finished fetching yandex_weather data in 0.962 seconds (success: True)
2022-01-29 16:07:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 192, in post
return await super().post(request)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/yandex_weather/config_flow.py", line 95, in async_step_init
data_schema=self._get_options_schema(),
File "/config/custom_components/yandex_weather/config_flow.py", line 101, in _get_options_schema
vol.Required(CONF_API_KEY, default=get_value(CONF_API_KEY)): str,
TypeError: get_value() missing 1 required positional argument: 'param'`

**Comment by IATkachenko** [comment]
Спасибо.
Исправлено в v0.5.1. Убрал с него флаг beta и можно обновиться.
