### ISSUE TITLE
Ошибка работы сервиса при Weather condition images: HomeAssistant

### ISSUE THREAD

**Issue by scaytrase** [IATkachenko/HA-YandexWeather#67]
При вот таких настройках

![image](https://user-images.githubusercontent.com/6578413/227913655-aea904e6-c217-4540-805f-bf9e3166eba7.png)

Получаю в логе вот такое исключение:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/yandex_weather/const.py:181
Integration: Yandex Weather (documentation, issues)
First occurred: March 25, 2023 at 16:53:19 (67 occurrences)
Last logged: 12:53:31

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/config/custom_components/yandex_weather/weather.py", line 186, in _handle_coordinator_update
    self._attr_entity_picture = get_image(
  File "/config/custom_components/yandex_weather/const.py", line 181, in get_image
    if CONDITION_IMAGE[image_source]["mapping"] is None
KeyError: 'mapping'
```

Ломается сервис `weather.yandex_weather` и становится unavailable. при этом погода продолжает обновляться и отдельные энтити продолжают работать, но карточка погоды на дашборде отваливается из-за пропадания сервиса.

Я поперетыкивал источники картинок - и все вроде пока работает, если вдруг пойму с чем связано (вроде ребут, релоад интеграции и смена настроек не сломали ничего) - допишу

Версия компонента 2.0.1
HA 2023.3.4

**Comment by IATkachenko** [comment]
Доброго дня.

Спасибо!
Вижу где и как нарушена логика. В ближайшее время (надеюсь успеть до выхода `2023.4`) поправлю.

**Comment by IATkachenko** [comment]
Исправлено в [v2.0.2](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v2.0.2)
