### ISSUE TITLE
После 01.04.2023 api ключ стал не валиден. 

### ISSUE THREAD

**Issue by kirillisprk** [IATkachenko/HA-YandexWeather#72]
### В чем проблема?

Добрый день. 
После 1 апреля перестала отображаться погода. 
Жалуется на не правильный ключ, хотя я его не менял. И до этого полгода все было нормально. 
При этом в личном кабинете видно что лимит запросов расходуется.

### При использовании какой версии интеграции возникает проблема?

2.0.3

### Какая версия Home Assistant используется?

2023.3.6

### Какой способ установки Home Assistant используется?

Home Assistant Core

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

### Есть что-нибудь полезное в логе?

```txt
error_log.docx
Файл можно получить по ссылке:
error_log.docx
https://disk.yandex.ru/i/n5NXQ4fhKTGt6A
```

**Comment by IATkachenko** [comment]
@kirillisprk, добрый день.

В логах ошибок ключа не вижу.
5 апреля интеграциия успешно получила данные:
```
2023-04-05 09:18:54.033 DEBUG (MainThread) [custom_components.yandex_weather.updater] {"now":1680661133,"now_dt":"2023-04-05T02:18:53.852092Z"
...
```

и свалилась с ошибкой из закрепленного (и уже исправленного) issue #70 
```
2023-04-05 09:18:54.328 ERROR (MainThread) [custom_components.yandex_weather.updater] Unexpected error fetching Yandex Weather updater data: 'prec_mm'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/yandex_weather/updater.py", line 240, in update
    forecast[ATTR_FORECAST_NATIVE_PRECIPITATION] = f["prec_mm"]  # type: ignore
KeyError: 'prec_mm'
2023-04-05 09:18:54.332 DEBUG (MainThread) [custom_components.yandex_weather.updater] Finished fetching Yandex Weather updater data in 9.847 seconds (success: False)
```

Обновитесь до [v2.0.3](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v2.0.3), в которой эта проблема была исправлена.

**Comment by kirillisprk** [comment]
Да вы были правы, обновление установил но HA не перезапускал.  Проблема ушла. Спасибо большое !
