### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by alexls74** [IATkachenko/HA-YandexWeather#84]
### В чем проблема?

После последнего обновления перестала запускаться.

### При использовании какой версии интеграции возникает проблема?

3.1.1

### Какая версия Home Assistant используется?

core-2023.7.3

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

### Есть что-нибудь полезное в логе?

```txt
Logger: homeassistant.setup
Source: custom_components/yandex_weather/updater.py:14 
Integration: yandex_weather (documentation, issues) 
First occurred: 12:28:46 (1 occurrences) 
Last logged: 12:28:46

Setup failed for custom integration yandex_weather: Unable to import component: cannot import name 'ATTR_FORECAST_IS_DAYTIME' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/__init__.py", line 11, in <module>
    from .config_flow import get_value
  File "/config/custom_components/yandex_weather/config_flow.py", line 22, in <module>
    from .updater import WeatherUpdater
  File "/config/custom_components/yandex_weather/updater.py", line 14, in <module>
    from homeassistant.components.weather import (
ImportError: cannot import name 'ATTR_FORECAST_IS_DAYTIME' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
```

**Comment by fmobile999** [comment]
То же самое
`Logger: homeassistant.setup
Source: custom_components/yandex_weather/updater.py:14
Integration: yandex_weather ([documentation](https://github.com/IATkachenko/HA-YandexWeather/wiki), [issues](https://github.com/IATkachenko/HA-YandexWeather/issues))
First occurred: 12 августа 2023 г. в 03:34:25 (1 occurrences)
Last logged: 12 августа 2023 г. в 03:34:25
Setup failed for custom integration yandex_weather: Unable to import component: cannot import name 'ATTR_FORECAST_IS_DAYTIME' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/__init__.py", line 11, in <module>
    from .config_flow import get_value
  File "/config/custom_components/yandex_weather/config_flow.py", line 22, in <module>
    from .updater import WeatherUpdater
  File "/config/custom_components/yandex_weather/updater.py", line 14, in <module>
    from homeassistant.components.weather import (
ImportError: cannot import name 'ATTR_FORECAST_IS_DAYTIME' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)`

**Comment by IATkachenko** [comment]
Хм...
Таки поломал обратную совместимость :( сори.
Нужно или откатить интеграцию на предыдущую версию или обновить HA.
Сейчас поправлю HACS
