### ISSUE TITLE
Интеграция HA-YandexWeather перестала работать в HA 2024.1.0

### ISSUE THREAD

**Issue by vkogan2005** [IATkachenko/HA-YandexWeather#90]
### В чем проблема?

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 00:21:54 (1 occurrences)
Last logged: 00:21:54
```
Unexpected exception importing platform custom_components.yandex_weather.weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/weather.py", line 74, in <module>
    class YandexWeather(WeatherEntity, CoordinatorEntity, RestoreEntity):
  File "/config/custom_components/yandex_weather/weather.py", line 230, in YandexWeather
    @WeatherEntity.condition.setter
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cached_property' object has no attribute 'setter'
```

### При использовании какой версии интеграции возникает проблема?

3.1.1

### Какая версия Home Assistant используется?

core-2024.1.0

### Какой способ установки Home Assistant используется?

Home Assistant OS

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

### Есть что-нибудь полезное в логе?

```txt
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 00:21:54 (1 occurrences)
Last logged: 00:21:54

Unexpected exception importing platform custom_components.yandex_weather.weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/weather.py", line 74, in <module>
    class YandexWeather(WeatherEntity, CoordinatorEntity, RestoreEntity):
  File "/config/custom_components/yandex_weather/weather.py", line 230, in YandexWeather
    @WeatherEntity.condition.setter
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cached_property' object has no attribute 'setter'
```

**Comment by LordArrin** [comment]
![Screenshot_20240104-092152_Home Assistant](https://github.com/IATkachenko/HA-YandexWeather/assets/79581469/12f307df-b4a6-477b-9e37-2e979f10d876)
Logger: homeassistant.config_entries
Source: config_entries.py:561
First occurred: 07:24:30 (6 occurrences)
Last logged: 09:17:51

Error unloading entry Яндекс.Погода for sensor
Error unloading entry Яндекс.Погода for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 152, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!


Same error here.

**Comment by alex-msk** [comment]
Та же проблема

**Comment by siaua** [comment]
Присоединяюсь

**Comment by Gmarapet** [comment]
Та же проблема.

**Comment by Skeptik966** [comment]
Такая же проблема после обновления на версию HA 2024.1.0

**Comment by Timuridze1** [comment]
Подтверждаю

**Comment by destman** [comment]
Скорее всего связанно с этим:
https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation

В gw3 та же беда.
https://github.com/AlexxIT/XiaomiGateway3/pull/1246

**Comment by dronix27** [comment]
> Скорее всего связанно с этим: https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation
> 
> В gw3 та же беда. [AlexxIT/XiaomiGateway3#1246](https://github.com/AlexxIT/XiaomiGateway3/pull/1246)

Верно. А решить-то как? Для программистов уровня копипаста )))

**Comment by vkogan2005** [comment]
> > Скорее всего связанно с этим: https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation
> > В gw3 та же беда. [AlexxIT/XiaomiGateway3#1246](https://github.com/AlexxIT/XiaomiGateway3/pull/1246)
> 
> Верно. А решить-то как? Для программистов уровня копипаста )))

Для Yandex Weather закомментить 230ю строку в custom_components/yandex_weather/weather.py

**Comment by dronix27** [comment]
> > > Скорее всего связанно с этим: https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation
> > > В gw3 та же беда. [AlexxIT/XiaomiGateway3#1246](https://github.com/AlexxIT/XiaomiGateway3/pull/1246)
> > 
> > 
> > Верно. А решить-то как? Для программистов уровня копипаста )))
> 
> Для Yandex Weather закомментить 230ю строку в custom_components/yandex_weather/weather.py Должно быть так: #@WeatherEntity.condition.setter

Да. Теперь работает.

**Comment by zzaal** [comment]
> Для Yandex Weather закомментить 230ю строку в custom_components/yandex_weather/weather.py
> Должно быть так: #@WeatherEntity.condition.setter

Спасибо!!!
С Новым Годом!

**Comment by AndreyKurilovich** [comment]
> > > Скорее всего связанно с этим: https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation
> > > В gw3 та же беда. [AlexxIT/XiaomiGateway3#1246](https://github.com/AlexxIT/XiaomiGateway3/pull/1246)
> > 
> > 
> > Верно. А решить-то как? Для программистов уровня копипаста )))
> 
> Для Yandex Weather закомментить 230ю строку в custom_components/yandex_weather/weather.py Должно быть так: #@WeatherEntity.condition.setter

Огромное спасибо!

**Comment by IgorA-XXI** [comment]
У меня при загрузке интеграции в 2024.1.0 она уходит в бесконечную рекурсию - RecursionError: maximum recursion depth exceeded :(

2024-01-05 06:56:12.426 ERROR (MainThread) [homeassistant.components.weather] Error adding entities for domain weather with platform yandex_weather
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1277, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/yandex_weather/weather.py", line 197, in async_added_to_hass
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 953, in _stringify_state
    return str(state)
           ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1485, in __repr__
    return f"<entity {self.entity_id}={self._stringify_state(self.available)}>"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 953, in _stringify_state
    return str(state)
           ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1485, in __repr__
    return f"<entity {self.entity_id}={self._stringify_state(self.available)}>"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 953, in _stringify_state
    return str(state)
           ^^^^^^^^^^
...и дальше последние две строки повторяются до RecursionError: maximum recursion depth exceeded.

Предложенное исправление не помогает - это явно другая ошибка, тоже связанная с переходом на 2024.1.0... аналогичное поведение наблюдалось и в других интеграциях после перехода.

**Comment by sweethome29** [comment]
Это у тебя что то, друг. 
Изначальная проблема в том что отвалился weather. домен у интеграции в 2024.1. и закоментить 230 строку сработало. Спасибо предложившему решение) Все остальные сенсоры работали как и раньше.
Могу тебе лишь посоветовать соблюдать таймаут по запросам на бесплатном тарифе. И перезагружать ха с этой интеграцией не чаще 30 минут.

**Comment by ironkiss** [comment]
в 2024.1.1 опять перестало работать, закомментировал, но не помого.

**Comment by FlintFD** [comment]
Присоединяюсь, 2024.1.1 опять не работает

**Comment by vkogan2005** [comment]
> Присоединяюсь, 2024.1.1 опять не работает

Всё работает. Перезагрузите интеграцию. К сожалению, пока только так)

**Comment by IATkachenko** [comment]
Уххх... съездил отдохнуть... Сейчас гляну что там наделали в `2024.1`.
Через пару часов выкачу фикс релиз

**Comment by Gmarapet** [comment]
> Уххх... съездил отдохнуть... Сейчас гляну что там наделали в `2024.1`.
> Через пару часов выкачу фикс релиз

Там уже 2024.1.2 выкатили. )

**Comment by IATkachenko** [comment]
Исправлено в [v3.1.2](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.1.2)

**Comment by jankin-y** [comment]
Спасибо, v3.1.2 все поднялось без ошибок на 2024.1.2!
