### ISSUE TITLE
Объект weather.* не предоставляется службой после обновления HA 2024.1

### ISSUE THREAD

**Issue by 1iverea9er** [IATkachenko/HA-YandexWeather#94]
### В чем проблема?

После обновления HA до версии 2024.1 объект более не предоставляется службой yandex_weather.weather

### При использовании какой версии интеграции возникает проблема?

3.1.1

### Какая версия Home Assistant используется?

2024.1

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

### Есть что-нибудь полезное в логе?

```txt
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 18:59:50 (1 occurrences)
Last logged: 18:59:50

Unable to prepare setup for platform 'yandex_weather.weather': Platform not found (Exception importing custom_components.yandex_weather.weather).



Logger: homeassistant.loader
Source: loader.py:842
First occurred: 18:59:50 (1 occurrences)
Last logged: 18:59:50

Unexpected exception importing platform custom_components.yandex_weather.weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/weather.py", line 74, in <module>
    class YandexWeather(WeatherEntity, CoordinatorEntity, RestoreEntity):
  File "/config/custom_components/yandex_weather/weather.py", line 230, in YandexWeather
    @WeatherEntity.condition.setter
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cached_property' object has no attribute 'setter'
```

**Comment by IATkachenko** [comment]
Повтор #90
Исправлено в v3.1.2
